# Generated by Django 6.0 on 2025-12-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP клієнт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Кількість замовлень')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума покупок')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['is_vip'], name='clients_cli_is_vip_465feb_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'), models.Index(fields=['-created_at'], name='clients_cli_created_552574_idx')],
            },
        ),
    ]
